"""empty message

Revision ID: e64bbd77662e
Revises: da2637ad5172
Create Date: 2018-10-22 04:48:10.729566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64bbd77662e'
down_revision = 'da2637ad5172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_b', sa.Integer(), nullable=True),
    sa.Column('user_w', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('user_active', sa.String(length=80), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
